name = "dacici"
compatibility_date = "2025-09-28"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liQJy5dKVSjDqiAD"
GITHUB_OWNER = "soho1319"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dacici.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://dacici.pages.dev"

